### ISSUE TITLE
can this code work well

### ISSUE THREAD

**Issue by zhyj3038** [mowayao/yolo_gluon#1]
hi,thankc very much foer your awearsome work.!
I clone your code and try runing, but the detect result is so bad.
I wonder this is a finished project?

**Comment by mowayao** [comment]
This is only a naive implementation of YOLO, some parameters are different with the paper.

**Comment by mowayao** [comment]
By the way, you need to run train_yolo.py firstly, then uncomment the loading code in demo.py then run it.

**Comment by zhyj3038** [comment]
thanks ^^
